[meta]
  title = ""
  description = ""
  author = ""
  useCase = "Live"
  language = "JavaScript"
  framework = "Next"

[build]
  command = "npm install"

[config]
  sample = "sample.env.local"
  output = ".env.local"

[post-build]
  message = "Run `npm run dev` to get up and running locally."
