name: Build Docker Container & Push to Registry

on:
    workflow_call:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test_fastapi_job:
        uses: junruxiong/parakeetai/.github/workflows/test-fastapi.yaml@main
    docker_build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend-py
        needs: [test_fastapi_job]
        env:
            CLUSTER_NAME: AItoyK8s

        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
            - name: Azure login
              id: login
              uses: azure/login@v1.4.3
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Azure Container Registry login
              run: |
                  az acr login --name ${{ secrets.REGISTRY }}
            - name: Set AKS context
              id: set-context
              uses: azure/aks-set-context@v3
              with:
                  resource-group: "${{ secrets.resource_group }}"
                  cluster-name: "${{ secrets.cluster_name }}"
            - name: Build container image
              run: |
                  docker build --tag aitoy:latest .
            - name: Manually tag the built image with custom tags
              run: |
                  docker tag aitoy:latest aitoyregistry.azurecr.io/aitoy:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
            - name: Push all tagged images to the registry
              run: |
                  docker push aitoyregistry.azurecr.io/aitoy --all-tags
