name: Build Docker Container & Push to Registry

on:
    workflow_call:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test_fastapi_job:
        uses: akdeb/parakeetai/.github/workflows/test-fastapi.yaml@main
    docker_build:
        runs-on: ubuntu-latest
        needs: [test_fastapi_job]
        env:
            CLUSTER_NAME: AItoyK8s
